resources:
- flux-ns.yaml
- memcache-svc.yaml
- memcache-dep.yaml
- flux-account.yaml
- flux-secret.yaml
- flux-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app.kubernetes.io/version: v1.25.4
  catalog.kubestack.com/heritage: kubestack.com/catalog/flux
  catalog.kubestack.com/variant: base
commonLabels:
  app.kubernetes.io/component: controller
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: flux
